spring:
  application:
    name: investment_be

  datasource:
    url: jdbc:postgresql://localhost:5432/investmentAppDB
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081